version: '3.8'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      # Configure Metabase to use an external Postgres - values taken from environment or .env file
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT:-5432}
      MB_DB_HOST: ${MB_DB_HOST}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_JETTY_PORT: 3000
    volumes:
      - metabase-data:/metabase-data
    restart: unless-stopped

volumes:
  metabase-data:
